export const allMembers = [
    [
        {
            name: "Reuben Devanesan",
            position: "Academic Secretary",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "98676 08536",
            imgSrc: "./Images/Reuben Devanesan.webp",
            linkedin: "https://www.linkedin.com/in/reuben-devanesan/",
            www: "",
            email: "reuben.sd@iitgn.ac.in"
        },
        {
            name: "Yash Khandelwal",
            position: "Special Advisor",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "73740 16840",
            imgSrc: "./Images/Yash Khandelwal.webp",
            linkedin: "https://www.linkedin.com/in/yash-khandelwal-5a7a6b212/",
            www: "",
            email: "yash.khandelwal@iitgn.ac.in"
        },
        {
            name: "Kalash Kankaria",
            position: "Special Advisor",
            ug: "Senior Undergraduate",
            branch: "Computer Science Engineer",
            contact: "93140 27008",
            imgSrc: "./Images/Kalash Kankaria.webp",
            linkedin: "https://www.linkedin.com/in/kalash-kankaria-2a7522202/",
            www: "",
            email: "kalash.kankaria@iitgn.ac.in"
        },
        {
            name: "Adit Rambhia",
            position: "Coordinator for Events & Initiatives",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "93140 27008",
            imgSrc: "./Images/Adit profile.webp",
            linkedin: "https://www.linkedin.com/in/adit-rambhia/",
            www: "",
            email: "rambhiaadit@iitgn.ac.in"
        },
        {
            name: "Aaryan Darad",
            position: "Coordinator for Events & Initiatives",
            ug: "Junior Undergraduate",
            branch: "Chemical Engineer",
            contact: "99985 83773",
            imgSrc: "./Images/AaryanDarad.webp",
            linkedin: "https://www.linkedin.com/in/aaryan-darad-b1351a1ab/",
            www: "",
            email: "daradaaryan@iitgn.ac.in"
        },
        {
            name: "Vikash Beniwal",
            position: "Coordinator for Peer Assisted Learning",
            ug: "Junior Undergraduate",
            branch: "Chemical Engineer",
            contact: "63679 22581",
            imgSrc: "./Images/vikash.webp",
            linkedin: "https://www.linkedin.com/in/vikash-kumar-beniwal-656068228/",
            www: "",
            email: "beniwalvikash@iitgn.ac.in"
        },
        {
            name: "Aditya Gupte",
            position: "Coordinator for Academic Discussion Hours",
            ug: "Junior Undergraduate",
            branch: "Chemical Engineer",
            contact: "96644 88377",
            imgSrc: "./Images/AdityaGupte.webp",
            linkedin: "https://www.linkedin.com/in/aditya-gupte-bb404422b/",
            www: "",
            email: "adityaaditya@iitgn.ac.in"
        },
        {
            name: "Yash Ahire",
            position: "Coordinator for Class Representatives and Course Feedback",
            ug: "Junior Undergraduate",
            branch: "Chemical Engineer",
            contact: "72191 93716",
            imgSrc: "./Images/Yash Ahire.webp",
            linkedin: "",
            www: "",
            email: "yashahire@iitgn.ac.in"
        },
        {
            name: "Madhav Kanda",
            position: "Coordinator for Documentation & Outreach",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "97268 83487",
            imgSrc: "./Images/Madhav Kanda.webp",
            linkedin: "",
            www: "",
            email: "madhav.kanda@iitgn.ac.in"
        },
        {
            name: "Nishant Tatar",
            position: "Coordinator for Documentation & Outreach",
            ug: "Junior Undergraduate",
            branch: "Chemical Engineer",
            contact: "8530 32662",
            imgSrc: "./Images/index.webp",
            linkedin: "",
            www: "",
            email: "madhav.kanda@iitgn.ac.in"
        },
        {
            name: "Netram Choudhary",
            position: "Webmaster",
            ug: "Junior Undergraduate",
            branch: "Chemical Engineer",
            contact: "78771 92651",
            imgSrc: "./Images/NetramChoudhary.webp",
            linkedin: "",
            www: "",
            email: "choudharynetram@iitgn.ac.in"
        },
        {
            name: "Parth Govale",
            position: "Webmaster",
            ug: "Sophomore",
            branch: "Computer Science Engineer",
            contact: "96198 69044",
            imgSrc: "./Images/parth.webp",
            linkedin: "https://www.linkedin.com/in/parth-govale-a65120277/",
            www: "https://github.com/Demolus13",
            email: "parth.govale@iitgn.ac.in"
        },
        {
            name: "Anay Sisodiya",
            position: "Webmaster",
            ug: "Junior Undergraduate",
            branch: "Material Science Engineer",
            contact: "62638 18327",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "sisodiyaanay@iitgn.ac.in"
        },
        {
            name: "Birudugadda Srivibhav",
            position: "General Member",
            ug: "Sophomore",
            branch: "Material Science Engineer",
            contact: "93925 39193",
            imgSrc: "./Images/Birudugadda Srivibhav.webp",
            linkedin: "",
            www: "",
            email: "birudugadda.srivibhav@iitgn.ac.in"
        },
        {
            name: "Ishan Agarwal",
            position: "General Member",
            ug: "Sophomore",
            branch: "Material Science Engineer",
            contact: "91188 86527",
            imgSrc: "./Images/Ishan Agarwal.webp",
            linkedin: "",
            www: "",
            email: "ishan.agarwal@iitgn.ac.in"
        },
        {
            name: "Shrishti Mishra",
            position: "General Member",
            ug: "Sophomore",
            branch: "Material Science Engineer",
            contact: "92638 70017",
            imgSrc: "./Images/Shrishti Mishra.webp",
            linkedin: "",
            www: "",
            email: "shrishti.mishra@iitgn.ac.in"
        },
        {
            name: "Harsh Jain",
            position: "General Member",
            ug: "Sophomore",
            branch: "Material Science Engineer",
            contact: "98814 67068",
            imgSrc: "./Images/harsh.webp",
            linkedin: "https://www.linkedin.com/in/harsh-jain-449a19255/",
            www: "",
            email: "harsh.jain@iitgn.ac.in"
        },
        {
            name: "Mayank Dahotre",
            position: "General Member",
            ug: "Sophomore",
            branch: "Material Science Engineer",
            contact: "98237 50066",
            imgSrc: "./Images/fool.webp",
            linkedin: "",
            www: "",
            email: "mayank.dahotre@iitgn.ac.in"
        },
        {
            name: "Atharva Bodhale",
            position: "General Member",
            ug: "Sophomore",
            branch: "Material Science Engineer",
            contact: "90225 08427",
            imgSrc: "./Images/fool.webp",
            linkedin: "",
            www: "",
            email: "atharva.bodhale@iitgn.ac.in"
        },
        {
            name: "Shrey Agarwal",
            position: "General Member",
            ug: "Sophomore",
            branch: "Material Science Engineer",
            contact: "99271 66739",
            imgSrc: "./Images/Shrey Agarwal.webp",
            linkedin: "",
            www: "",
            email: "shrey.agarwal@iitgn.ac.in"
        },
        {
            name: "Jayashree Mahato",
            position: "Social Media Manager",
            ug: "Postgraduate",
            branch: "",
            contact: "62061 51114",
            imgSrc: "./Images/Jayashree.webp",
            linkedin: "",
            www: "",
            email: "jayashree.mahato@iitgn.ac.in"
        },
        {
            name: "Arul Singh",
            position: "Graphic Designer",
            ug: "Sophomore",
            branch: "Material Science Engineer",
            contact: "83197 12668",
            imgSrc: "./Images/Arul Singh.webp",
            linkedin: "",
            www: "",
            email: "arul.singh@iitgn.ac.in"
        },
    ],
    [
        {
            name: "Revant Shah",
            position: "Academic Secretary",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/Revant.webp",
            linkedin: "",
            www: "",
            email: "revant.s@alumni.iitgn.ac.in"
        },
        {
            name: "Reuben Devanesan",
            position: "Special Advisor",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer & Computer Science Engineer",
            contact: "98676 08536",
            imgSrc: "./Images/Reuben Devanesan.webp",
            linkedin: "",
            www: "",
            email: "reuben.sd@iitgn.ac.in"
        },
        {
            name: "Kalash Kankaria",
            position: "Coordinator for Events and Initiatives",
            ug: "Senior Undergraduate",
            branch: "Computer Science Engineer",
            contact: "93140 27008",
            imgSrc: "./Images/Kalash Kankaria.webp",
            linkedin: "",
            www: "",
            email: "kalash.kankaria@iitgn.ac.in"
        },
        {
            name: "Chaitanya Guntoorkar",
            position: "Coordinator for Peer Assisted Learning",
            ug: "Senior Undergraduate",
            branch: "Material Science Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "shashikant.gc@alumni.iitgn.ac.in"
        },
        {
            name: "Yash Khandelwal",
            position: "Coordinator for Academic Discussion Hours",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/Yash Khandelwal.webp",
            linkedin: "",
            www: "",
            email: "yash.khandelwal@iitgn.ac.in"
        },
        {
            name: "Deepak Patel",
            position: "Coordinator for Class Representatives and Course Feedback",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "deepak.p@alumni.iitgn.ac.in"
        },
        {
            name: "Eesha Kulkarni",
            position: "Coordinator for Documentation and Outreach",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/eesha.webp",
            linkedin: "",
            www: "",
            email: "eesha.kulkarni@iitgn.ac.in"
        },
        {
            name: "Aravind Krishna",
            position: "Webmaster",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "aravind.krishna@iitgn.ac.in"
        },
        {
            name: "Naman Dharmani",
            position: "Webmaster",
            ug: "Senior Undergraduate",
            branch: "Computer Science Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "dharmaninaman@iitgn.ac.in"
        },
        {
            name: "Zaqi Momin",
            position: "Webmaster",
            ug: "Senior Undergraduate",
            branch: "",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "zaqimomin@iitgn.ac.in"
        },
        {
            name: "Aditya Gupte",
            position: "General Member",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "96644 88377",
            imgSrc: "./Images/AdityaGupte.webp",
            linkedin: "",
            www: "",
            email: "adityaaditya@iitgn.ac.in"
        },
        {
            name: "Vipul Mergu",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "merguvipul@iitgn.ac.in"
        },
        {
            name: "Aditi Garg",
            position: "General Member",
            ug: "Senior Undergraduate",
            branch: "Material Science Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "gargaditi@iitgn.ac.in"
        },
        {
            name: "Madhav Kanda",
            position: "General Member",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/Madhav Kanda.webp",
            linkedin: "",
            www: "",
            email: "madhav.kanda@iitgn.ac.in"
        },
        {
            name: "Ritu Vaja",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "Computer Science Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "vajaritu@alumni.iitgn.ac.in"
        },
        {
            name: "Rahul Kumar Singh",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "Mechanical Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: ""
        },
        {
            name: "Amaan Ansari",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "Mechanical Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "amaan.ansari@iitgn.ac.in"
        },
        {
            name: "Archit Bahirat",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "Material Science Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "bahirat.archit@iitgn.ac.in"
        },
    ],
    [
        {
            name: "Bhavya Gupta",
            position: "Academic Secretary",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/bhavya.webp",
            linkedin: "",
            www: "",
            email: "bhavya.gupta@alumni.iitgn.ac.in"
        },
        {
            name: "Varun Dolia",
            position: "Special Advisor",
            ug: "Senior Undergraduate",
            branch: "Electric Engineer",
            contact: "",
            imgSrc: "./Images/Varun.webp",
            linkedin: "",
            www: "",
            email: "varun.jain@alumni.iitgn.ac.in"
        },
        {
            name: "Revant Shah",
            position: "Coordinator for Events and Initiatives",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/Revant.webp",
            linkedin: "",
            www: "",
            email: "revant.s@alumni.iitgn.ac.in"
        },
        {
            name: "Reuben Devanesan",
            position: "Coordinator for Peer Assisted Learning",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "98676 08536",
            imgSrc: "./Images/Reuben Devanesan.webp",
            linkedin: "",
            www: "",
            email: "reuben.sd@iitgn.ac.in"
        },
        {
            name: "Sresth Tosniwal",
            position: "Coordinator for Academic Discussion Hours",
            ug: "Senior Undergraduate",
            branch: "Mechanical Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "sresth.t@alumni.iitgn.ac.in"
        },
        {
            name: "Tejendra Patel",
            position: "Coordinator for Class Representatives and Course Feedback",
            ug: "Senior Undergraduate",
            branch: "Mechanical Engineer",
            contact: "",
            imgSrc: "./Images/tejendra.webp",
            linkedin: "",
            www: "",
            email: "tejendra.p@alumni.iitgn.ac.in"
        },
        {
            name: "Sanjay Venkitesh",
            position: "Coordinator for Documenattion and Outreach",
            ug: "Senior Undergraduate",
            branch: "Electric Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "venkitesh.s@alumni.iitgn.ac.in"
        },
        {
            name: "Gaurav Viramgami",
            position: "Webmaster",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/gaurav.webp",
            linkedin: "",
            www: "",
            email: "viramgami.g@alumni.iitgn.ac.in"
        },
        {
            name: "Aishwarya Omar",
            position: "General Member",
            ug: "Senior Undergraduate",
            branch: "Mechanical Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "aishwarya.omar@iitgn.ac.in"
        },
        {
            name: "Eesha Kulkarni",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/eesha.webp",
            linkedin: "",
            www: "",
            email: "merguvipul@iitgn.ac.in"
        },
        {
            name: "Guru Sharan N",
            position: "General Member",
            ug: "Senior Undergraduate",
            branch: "Material Science Engineer",
            contact: "",
            imgSrc: "./Images/guru.webp",
            linkedin: "",
            www: "",
            email: "gurusharan.n@iitgn.ac.in"
        },
        {
            name: "Kalash Kankaria",
            position: "General Member",
            ug: "Senior Undergraduate",
            branch: "Computer Science Engineer",
            contact: "93140 27008",
            imgSrc: "./Images/Kalash Kankaria.webp",
            linkedin: "",
            www: "",
            email: "kalash.kankaria@iitgn.ac.in"
        },
        {
            name: "Progyan Das",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "Computer Science Engineer",
            contact: "",
            imgSrc: "./Images/progyan.webp",
            linkedin: "",
            www: "",
            email: "progyan.das@iitgn.ac.in"
        },
        {
            name: "Saniya Patwardhan",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "Mechanical Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "patwardhan.saniya@iitgn.ac.in"
        },
        {
            name: "Sourav Yadav",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "Mechanical Engineer",
            contact: "",
            imgSrc: "./Images/sourav.webp",
            linkedin: "",
            www: "",
            email: "yadav.sourav@alumni.iitgn.ac.in"
        },
        {
            name: "Umang Agarwal",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "Material Science Engineer",
            contact: "",
            imgSrc: "./Images/umang.webp",
            linkedin: "",
            www: "",
            email: "agarwal.umang@alumni.iitgn.ac.in"
        },
    ],
    [
        {
            name: "Shantanu Jana",
            position: "Academic Secretary",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/shantanu.webp",
            linkedin: "",
            www: "",
            email: "shantanu.jana@alumni.iitgn.ac.in"
        },
        {
            name: "Nidhin Harilal",
            position: "Special Advisor",
            ug: "Senior Undergraduate",
            branch: "Computer Science Engineer",
            contact: "",
            imgSrc: "./Images/nidhin.webp",
            linkedin: "",
            www: "",
            email: "nidhin.harilal@alumni.iitgn.ac.in"
        },
        {
            name: "Anas Ali",
            position: "Coordinator for Events and Initiatives",
            ug: "Senior Undergraduate",
            branch: "Civil Engineer",
            contact: "",
            imgSrc: "./Images/anas.webp",
            linkedin: "",
            www: "",
            email: "anas.ali@alumni.iitgn.ac.in"
        },
        {
            name: "Abhiraj Bhasin",
            position: "Coordinator for Academic Discussion Hours",
            ug: "Senior Undergraduate",
            branch: "Mechanical Engineer",
            contact: "",
            imgSrc: "./Images/abhiraj.webp",
            linkedin: "",
            www: "",
            email: "abhiraj.bhasin@alumni.iitgn.ac.in"
        },
        {
            name: "Bhavya Gupta",
            position: "Coordinator for Class Representatives and Course Feedback",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/bhavya.webp",
            linkedin: "",
            www: "",
            email: "bhavya.gupta@alumni.iitgn.ac.in"
        },
        {
            name: "Revant Shah",
            position: "Coordinator for Documenattion and Outreach",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/Revant.webp",
            linkedin: "",
            www: "",
            email: "revant.s@alumni.iitgn.ac.in"
        },
        {
            name: "Reuben Devanesan",
            position: "Webmaster",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "98676 08536",
            imgSrc: "./Images/Reuben Devanesan.webp",
            linkedin: "",
            www: "",
            email: "reuben.sd@iitgn.ac.in"
        },
        {
            name: "Aditya Shekhar",
            position: "General Member and Webmaster",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/noimg.webp",
            linkedin: "",
            www: "",
            email: "aditya.ss@alumni.iitgn.ac.in"
        },
        {
            name: "Deepak Patel",
            position: "General Member",
            ug: "Senior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/deepak.webp",
            linkedin: "",
            www: "",
            email: "deepak.p@alumni.iitgn.ac.in"
        },
        {
            name: "Siddhi Surawar",
            position: "General Member",
            ug: "Junior Undergraduate",
            branch: "Chemical Engineer",
            contact: "",
            imgSrc: "./Images/siddhi.webp",
            linkedin: "",
            www: "",
            email: "siddhi.pravin@alumni.iitgn.ac.in"
        },
        {
            name: "G Gomathy",
            position: "General Member",
            ug: "Senior Undergraduate",
            branch: "Master of Arts",
            contact: "",
            imgSrc: "./Images/gomathy.webp",
            linkedin: "",
            www: "",
            email: "gomathy_g@alumni.iitgn.ac.in"
        },
    ]
]